# 由于成本问题，现已全面转向 Github Actions 构建
name: Build FRP Binaries

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Manual build tag'
        required: false
        default: 'manual'

permissions:
  contents: read

jobs:
  build:
    name: Build and Package FRP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip make gcc g++ upx

      - name: Run build script
        run: |
          chmod +x ./package.sh
          ./package.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frp-packages
          path: release/packages